apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotions
  labels:
    app: promotions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotions
  template:
    metadata:
      labels:
        app: promotions
    spec:
      containers:
        - name: promotions
          image: image-registry.openshift-image-registry.svc:5000/prakharredhat-dev/promotions:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_RUN_PORT
              value: "8080"
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: database_uri
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:8080", "wsgi:app"]
