apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
stringData:
  database-uri: "postgresql+psycopg://postgres:postgres@postgres:5432/postgres"
  database_uri: "sqlite:////tmp/test.db"
