apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: prakharredhat-dev
type: Opaque
data:
  # password = postgres
  password: cG9zdGdyZXM=
  # database_uri = postgresql+psycopg://postgres:postgres@postgres:5432/promotions
  database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAcG9zdGdyZXM6NTQzMi9wcm9tb3Rpb25z
