apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  description: Complete CD Pipeline for promotions service
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
    - name: branch
      type: string
      description: The git branch to clone
      default: "master"
    - name: image-name
      type: string
      description: The name of the image to build
      default: "promotions"
    - name: image-tag
      type: string
      description: The tag for the image
      default: "latest"
    - name: deployment-name
      type: string
      description: The name of the deployment to update
      default: "promotions"
    - name: service-url
      type: string
      description: The URL of the deployed service for BDD tests
  workspaces:
    - name: shared-workspace
  tasks:
    # Task 1: Clone the repository
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"

    # Task 2: Lint the code
    - name: lint
      taskRef:
        name: flake8-lint
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: source
          value: "service"

    # Task 3: Run unit tests
    - name: unit-tests
      taskRef:
        name: pytest-env
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: args
          value: "tests/ --cov=service --cov-report=html --cov-report=xml"

    # Task 4: Build and push image
    - name: build-image
      taskRef:
        name: build-and-push-image
      runAfter:
        - lint
        - unit-tests
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
        - name: registry
          value: "image-registry.openshift-image-registry.svc:5000"
        - name: namespace
          value: "prakharredhat-dev"

    # Task 5: Deploy to Kubernetes
    - name: deploy
      taskRef:
        name: deploy-image
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: deployment-name
          value: $(params.deployment-name)
        - name: image-url
          value: "image-registry.openshift-image-registry.svc:5000/prakharredhat-dev/$(params.image-name):$(params.image-tag)"

    # Task 6: Run BDD tests
    - name: bdd-tests
      taskRef:
        name: behave
      runAfter:
        - deploy
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: BASE_URL
          value: $(params.service-url)
