apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promotions-cd-pipeline
spec:
  description: CD pipeline to clone, lint, test, and build the promotions repository
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
      default: "https://github.com/CSCI-GA-2820-SU25-001/promotions.git"
    - name: revision
      type: string
      description: The git revision to checkout
      default: "main"
    - name: image-name
      type: string
      description: Name of the image to build
      default: "promotions"
    - name: image-tag
      type: string
      description: Tag for the image (will use commit SHA if available)
      default: "latest"
    - name: registry
      type: string
      description: Registry to push the image to
      default: "image-registry.openshift-image-registry.svc:5000"
    - name: namespace
      type: string
      description: Target namespace for deployment
      default: "default"
    - name: BASE_URL
      type: string
      description: "The URL of the deployed microservice"
      default: "http://your-service-route"
  workspaces:
    - name: shared-data
      description: Shared workspace for the pipeline
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)

    - name: lint-code
      taskRef:
        name: lint
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-data

    - name: run-unit-tests
      taskRef:
        name: unit-tests
      runAfter:
        - lint-code
      workspaces:
        - name: source
          workspace: shared-data

    - name: build-and-push-image
      taskRef:
        name: build-image-kaniko
      runAfter:
        - run-unit-tests
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE_NAME
          value: $(params.image-name)
        - name: IMAGE_TAG
          value: $(params.image-tag)
        - name: REGISTRY
          value: $(params.registry)

    - name: run-bdd-tests
      taskRef:
        name: run-bdd-tests
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: BASE_URL
          value: $(params.BASE_URL)

    - name: deploy-to-openshift
      taskRef:
        name: deploy-to-openshift
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE_NAME
          value: $(params.image-name)
        - name: IMAGE_TAG
          value: $(params.image-tag)
        - name: REGISTRY
          value: $(params.registry)
        - name: NAMESPACE
          value: $(params.namespace)
