apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: promotions-cd-pipeline
spec:
  description: CD pipeline to clone, lint, and test the promotions repository
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
      default: "https://github.com/CSCI-GA-2820-SU25-001/promotions.git"
    - name: revision
      type: string
      description: The git revision to checkout
      default: "main"
  workspaces:
    - name: shared-data
      description: Shared workspace for the pipeline
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)

    - name: lint-code
      taskRef:
        name: lint
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-data

    - name: run-unit-tests
      taskRef:
        name: unit-tests
      runAfter:
        - lint-code
      workspaces:
        - name: source
          workspace: shared-data
