apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: promotions-pipeline
  namespace: prakharredhat-dev
spec:
  description: Simple CD Pipeline for promotions service
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
    - name: branch
      type: string
      default: master
      description: The git branch to clone
    - name: image-name
      type: string
      default: promotions
      description: The name of the image to build

  workspaces:
    - name: shared-workspace

  tasks:
    # Task 1: Clone source code
    - name: clone
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    # Task 2: Lint code
    - name: lint
      runAfter: [clone]
      taskRef:
        kind: Task
        name: pylint
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: path
          value: service

    # Task 3: Run unit tests
    - name: test
      runAfter: [lint]
      taskRef:
        kind: Task
        name: pytest-env
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: pytest-args
          value:
            - tests/
            - --cov=service

    # Task 4: Build and push image
    - name: build
      runAfter: [test]
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/prakharredhat-dev/$(params.image-name):latest
        - name: DOCKERFILE
          value: ./Dockerfile

    # Task 5: Deploy application
    - name: deploy
      runAfter: [build]
      taskRef:
        kind: Task
        name: deploy-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: image-registry.openshift-image-registry.svc:5000/prakharredhat-dev/$(params.image-name):latest
        - name: manifest-dir
          value: k8s

    # Task 6: Run BDD tests
    - name: bdd
      runAfter: [deploy]
      taskRef:
        kind: Task
        name: behave
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: base-url
          value: http://promotions:80
        - name: wait-seconds
          value: "30"
        - name: driver
          value: "chrome"
