apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
  namespace: prakharredhat-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
