apiVersion: tekton.dev/v1beta1
kind: Task 
metadata:
  name: git-clone
spec:
  description: Clone a git repository
  params:
    - name: url
      type: string
      description: Repository URL to clone from
    - name: revision
      type: string
      description: Revision to checkout (branch, tag, sha, ref, etc...)
      default: "main"
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this Workspace
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -eu

        echo "Cloning $(params.url) at revision $(params.revision)"
        rm -rf .git
        rm -rf *
        git clone $(params.url) .
        git checkout $(params.revision)
        echo "Successfully cloned repository"
        echo "Current commit: $(git rev-parse HEAD)"
        ls -la
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  description: Run linting checks on Python code
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: flake8-lint
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -eu
        echo "Installing flake8 and pylint..."
        pip install --upgrade pip
        pip install flake8 pylint
        echo "Running flake8 syntax checks..."
        flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "Running full flake8 check..."
        flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
        echo "Running pylint..."
        pylint service tests --max-line-length=127 || echo "Pylint completed with warnings"
        echo "Linting completed successfully!"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unit-tests
spec:
  description: Run unit tests using pytest
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: run-tests
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -eu
        echo "Installing dependencies..."
        pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found, installing pytest only"
          pip install pytest
        fi
        echo "Running pytest..."
        pytest tests --maxfail=5 --disable-warnings --tb=short
        echo "Unit tests completed successfully!"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  description: Build and push Docker image using buildah
  params:
    - name: IMAGE_NAME
      type: string
      description: Name of the image to build
      default: "promotions"
    - name: IMAGE_TAG
      type: string
      description: Tag for the image
      default: "latest"
    - name: REGISTRY
      type: string
      description: Registry to push the image to
      default: "image-registry.openshift-image-registry.svc:5000"
    - name: DOCKERFILE
      type: string
      description: Path to the Dockerfile
      default: "./Dockerfile"
    - name: CONTEXT
      type: string
      description: Build context directory
      default: "."
    - name: TLSVERIFY
      type: string
      description: Verify the TLS on the registry endpoint
      default: "true"
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:v1.23.1
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      env:
        - name: STORAGE_DRIVER
          value: vfs
      script: |
        #!/bin/bash
        set -eu
        
        # Build the image
        echo "Building image $(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
        buildah --storage-driver=$(STORAGE_DRIVER) bud \
          --format=oci \
          --tls-verify=$(params.TLSVERIFY) \
          --no-cache \
          -f $(params.DOCKERFILE) \
          -t $(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG) \
          $(params.CONTEXT)
        
        # Push the image
        echo "Pushing image to registry..."
        buildah --storage-driver=$(STORAGE_DRIVER) push \
          --tls-verify=$(params.TLSVERIFY) \
          $(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG) \
          docker://$(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)
        
        echo "Image successfully built and pushed!"
        echo "Image: $(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-kaniko
spec:
  description: Build and push Docker image using Kaniko (no privileged access needed)
  params:
    - name: IMAGE_NAME
      type: string
      description: Name of the image to build
      default: "promotions"
    - name: IMAGE_TAG
      type: string
      description: Tag for the image
      default: "latest"
    - name: REGISTRY
      type: string
      description: Registry to push the image to
      default: "image-registry.openshift-image-registry.svc:5000"
    - name: DOCKERFILE
      type: string
      description: Path to the Dockerfile
      default: "./Dockerfile"
    - name: CONTEXT
      type: string
      description: Build context directory
      default: "."
  workspaces:
    - name: source
      description: The workspace containing the source code
    - name: dockerconfig
      description: An optional workspace that allows providing a .docker/config.json file
      optional: true
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.9.0-debug
      workingDir: $(workspaces.source.path)
      env:
        - name: DOCKER_CONFIG
          value: $(workspaces.dockerconfig.path)
      script: |
        #!/busybox/sh
        set -e
        
        echo "Building and pushing image with Kaniko..."
        echo "Context: $(params.CONTEXT)"
        echo "Dockerfile: $(params.DOCKERFILE)"
        echo "Destination: $(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
        
        /kaniko/executor \
          --dockerfile=$(params.DOCKERFILE) \
          --context=$(workspaces.source.path)/$(params.CONTEXT) \
          --destination=$(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG) \
          --skip-tls-verify \
          --cache=true
        
        echo "Image successfully built and pushed with Kaniko!"
        echo "Image: $(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-openshift
spec:
  description: Deploy the built image to OpenShift using oc commands
  params:
    - name: IMAGE_NAME
      type: string
      description: Name of the image to deploy
    - name: IMAGE_TAG
      type: string
      description: Tag of the image to deploy
    - name: REGISTRY
      type: string
      description: Registry where the image is stored
    - name: K8S_MANIFEST
      type: string
      description: Path to the Kubernetes manifest file
      default: "k8s/deployment.yaml"
  steps:
    - name: update-manifest
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        set -e
        echo "Updating image in manifest..."
        sed -i "s|IMAGE_PLACEHOLDER|$(params.REGISTRY)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)|g" $(params.K8S_MANIFEST)
    - name: apply-manifest
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        set -e
        echo "Applying manifest to OpenShift..."
        oc apply -f $(params.K8S_MANIFEST)
    - name: check-rollout
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        set -e
        DEPLOYMENT_NAME=$(grep 'name:' $(params.K8S_MANIFEST) | head -1 | awk '{print $2}')
        echo "Checking deployment rollout status for $DEPLOYMENT_NAME..."
        oc rollout status deployment/$DEPLOYMENT_NAME
