apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: promotions-github-binding
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.ref)
    - name: git-commit-sha
      value: $(body.after)
