name: Promotions Microservice CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: Promotions
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --system --dev

    - name: Linting
      run: |
        flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
        pylint service tests --max-line-length=127

    - name: Run Unit Tests
      run: pytest --pspec --cov=service --cov-fail-under=95 --cov-report=xml
      env:
        DATABASE_URI: postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/Promotions
    
    - name: Install system tools (if needed for Codecov)
      run: apt update && apt install -y git curl gpg
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: CSCI-GA-2820-SU25-001/promotions